FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app ./app
COPY ../frontend ./frontend
RUN mkdir -p /app/media
ENV FRONTEND_DIR=/app/frontend
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","${PORT:-8000}"]
